sudo: false
language: rust
cache:
  cargo: true
matrix:
  fast_finish: true
  include:
    - os: linux
      rust: stable
      # env: DO_COVERAGE=true
    - os: linux
      rust: beta
    - os: linux
      rust: nightly
    - os: osx
      rust: stable
  allow_failures:
    - rust: nightly

before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - which rustfmt || cargo install rustfmt
script:
  - cargo fmt -- --write-mode=diff
  - cargo build --verbose
  - cargo test --verbose
